---
- name: add postgres user
  become: yes
  become_user: postgres
  postgresql_user: name="{{ datoca.database.user }}" password="{{ datoca.database.password }}" role_attr_flags=CREATEDB,NOSUPERUSER

- name: create application database
  become: yes
  become_user: postgres
  postgresql_db: name="{{ datoca.database.name }}" encoding='UTF-8' owner="{{ datoca.database.user }}"

- name: add hstore extension
  become: yes
  become_user: postgres
  postgresql_ext: name=hstore db="{{ datoca.database.name }}"
